# Generated by Django 3.1.4 on 2021-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='nie dodano'),
            preserve_default=False,
        ),
    ]
