# Generated by Django 3.1.4 on 2021-01-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_recipe_preparation'),
        ('jedzonko', '0002_auto_20210107_0507'),
    ]

    operations = [
    ]
