# Generated by Django 2.2.6 on 2021-01-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20210107_0507'),
        ('jedzonko', '0002_recipe_preparation'),
    ]

    operations = [
    ]
