# Generated by Django 3.1.4 on 2021-01-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_merge_20210108_1009'),
        ('jedzonko', '0003_merge_20210108_1137'),
    ]

    operations = [
    ]
