# Generated by Django 2.2.6 on 2021-01-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_merge_20210108_1137'),
        ('jedzonko', '0003_merge_20210108_1009'),
    ]

    operations = [
    ]
