# Generated by Django 2.2.6 on 2021-01-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_merge_20210109_1540'),
        ('jedzonko', '0004_merge_20210109_1441'),
    ]

    operations = [
    ]
